### ISSUE TITLE
Health/Prayer bars

### ISSUE THREAD

**Issue by OrionAF** [SirHitech/MapleXPBar#1]
Could you add support for health bar and Prayer bar?  And maybe have multiple so you can have XP, health and Prayer?

**Comment by SirHitech** [comment]
Adding the option to display health or prayer sounds good, however my worry with having multiple at once is cluttering the area where split private chat is - which is the reason why the bar is pretty thin to begin with. I'll play around with a few ideas, and I'll take any suggestions for displaying them.

**Comment by OrionAF** [comment]
Is it possible to move the split private chat like you can move the minimap?  If you can, you could have a toggle-able option to move split private chat when using 2-3 bars.

**Comment by SirHitech** [comment]
Moving split chat would be one solution, however I'm not aware of how to do that.
I made this mockup of health, prayer, and xp bars all together, and it actually came out much nicer than I had expected. What do you think?
![MapleXPBar with health and prayer](https://user-images.githubusercontent.com/16417862/149039218-2c7bd1e6-eefc-4a95-b1d2-08cc5f86ca2b.png)

**Comment by OrionAF** [comment]
That looks pretty good.  Would it be possible to have a toggleable option to have them stackable?  I personally don't use split chat so for those of us who don't use it, it could work out.

**Comment by SirHitech** [comment]
Yeah, I don't see why not! Let's go with that then.

**Comment by OrionAF** [comment]
Awesome 😀

**Comment by SirHitech** [comment]
Alrighty, we've got a toggle to add the health and prayer bars, colors for the new bars, and I threw in the ability to color the notches for each bar since the default prayer color doesn't work well with the light notches I was using before.
![MapleXPBar with health and prayer - stacked](https://user-images.githubusercontent.com/16417862/149060924-53844b81-906a-4c89-a456-a9ab12984f8c.png)

**Comment by OrionAF** [comment]
Ohh that's awesome 😀

**Comment by SirHitech** [comment]
Great to hear! I'm gonna mess around and make sure nothing is broken with it, and if it seems stable I'll open the merge request for the main runelite repo.

**Comment by OrionAF** [comment]
Looking forward to it 😀

**Comment by SirHitech** [comment]
Code is live, let me know how it is.

**Comment by OrionAF** [comment]
That looks awesome, thank you 😀

**Comment by OrionAF** [comment]
hmmm, quick question.  How would the HP bar act if you drink a brew or eat a over the HP cap food?

**Comment by SirHitech** [comment]
It handles boosted health or prayer as if it's your max, so the bar shouldn't bug out if you have it boosted. I've only tested it on a +2 prayer altar since I only have membership on a GIM, and don't have brews or anything easy to test the HP with. So basically any boosted hp/pray will just show as full until you drop below your true max hp/pray.

**Comment by OrionAF** [comment]
aah okay, awesome :D
